### ISSUE TITLE
[Bug]: AttributeError: 'Model' object has no attribute 'to'

### ISSUE THREAD

**Issue by NoSadness** [towhee-io/towhee#2376] opened 2023-02-01 05:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**The code:**
import towhee
from towhee.trainer.training_config import TrainingConfig
from torchvision.datasets import ImageFolder

train_data_dir='D:\\project\\data\\reverse_image_search\\train'
test_data_dir='D:\\project\\data\\reverse_image_search\\test'
train_data = ImageFolder(train_data_dir)
eval_data = ImageFolder(test_data_dir)
training_config = TrainingConfig(
    batch_size=4,
    epoch_num=16,
    dataloader_num_workers=8
)
op = towhee.ops.image_embedding.timm(model_name='resnext101', num_classes=100).get_op()
op.train(training_config, train_dataset=train_data, eval_dataset=eval_data)

**The following error occurs when running the above code:**
Traceback (most recent call last):
  File "D:\software\pycharm\pythonProjects\fineTuningTest.py", line 15, in <module>
    op.train(training_config, train_dataset=train_data, eval_dataset=eval_data)
  File "D:\software\python\install\lib\site-packages\towhee\operator\base.py", line 158, in train
    self.trainer.train(resume_checkpoint_path)
  File "D:\software\python\install\lib\site-packages\towhee\trainer\trainer.py", line 224, in train
    self.run_train(None, None, resume_checkpoint_path)
  File "D:\software\python\install\lib\site-packages\towhee\trainer\trainer.py", line 298, in run_train
    self.model = self.model.to(self.configs.device)
AttributeError: 'Model' object has no attribute 'to'

### Expected Behavior

For the latest version of towhee, are there any articles or examples on how to fine-tuning?

### Environment

```markdown
- Towhee version:0.9.0
- OS: windows
- CPU/Memory:
- GPU:
- Others:
```

**Comment by jaelgu** [comment] 2023-02-01 06:29
The error is caused by change of [`image_embedding.timm`](https://towhee.io/image-embedding/timm) operator. It will be fixed in a linked pr.
For tutorial of training image model, please refer to the operator REAME page.

**Closed** 2023-02-01 07:21 UTC
Labels: kind/bug

**Comment by NoSadness** [comment] 2023-02-01 07:25
> The error is caused by change of [`image_embedding.timm`](https://towhee.io/image-embedding/timm) operator. It will be fixed in a linked pr soon. For tutorial of training image model, please refer to the operator REAME page.

Ok,thanks~
