### ISSUE TITLE
[Bug]: Fail to launch terminal in Quick Start

### ISSUE THREAD

**Issue by jaelgu** [towhee-io/towhee#1177] opened 2022-05-05 02:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Click "Launch Terminal" at https://docs.towhee.io/Getting%20Started/quick-start/ :

"This environment is no longer available."

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/86251631/166854696-928e703a-de70-4bcb-b6b1-9f3fd0c8be77.png">

### Expected Behavior

Be able to launch terminal and run example commands at Quick Start.

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by binbinlv** [comment] 2022-05-05 02:25
@Tumao727 

could you help to investigate this? Thanks

**Comment by Tumao727** [comment] 2022-05-05 02:33
I can't reproduce the problem...

<img width="1470" alt="截屏2022-05-05 上午10 30 05" src="https://user-images.githubusercontent.com/20420181/166855875-6f57cf16-880d-49e2-8ee3-0fa85266ccea.png">

**Comment by binbinlv** [comment] 2022-05-05 02:36
I try this too and it is the same with @jaelgu 

```
Your Interactive Learning Environment Bash Terminal

Error Details: Environment not starting correctly.
```

**Comment by binbinlv** [comment] 2022-05-05 02:41
Close the VPN, and it is OK now.

**Comment by fzliu** [comment] 2022-05-07 06:13
Closing this as many of us were unable to reproduce this issue (myself included). As @binbinlv mentioned, it seems to be due to VPN usage.

**Closed by fzliu** 2022-05-07 06:13 UTC
Labels: kind/bug, needs-triage, kind/documentation
