### ISSUE TITLE
[Bug]: Tried towhee example , rasie an error"NameError: name 'Some' is not defined"

### ISSUE THREAD

**Issue by jingkl** [towhee-io/towhee#890] opened 2022-03-22 11:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I think the relevant function definition is missing in the case
https://towhee.readthedocs.io/en/main/data_collection/option.html
```
>>> import towhee
>>> from towhee.functional import DataCollection
>>> a = Some(10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Some' is not defined
>>> b = Empty()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Empty' is not defined
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.5.1.dev69
- OS(Ubuntu or CentOS):macos
- CPU/Memory:
- GPU:
- Others:
```

**Comment by reiase** [comment] 2022-03-22 11:27
Duplicate of #891

**Comment by binbinlv** [comment] 2022-03-30 08:18
Verified, but not fixed, so reopened.

**Closed** 2022-03-30 10:29 UTC
Labels: kind/bug

**Comment by jingkl** [comment] 2022-03-30 10:30
There is a partial duplication of issue #962
